### ISSUE TITLE
希腊字母 θ 显示问题仍未解决

### ISSUE THREAD

**Issue by WyxXu** [chiron-fonts/chiron-sung-hk#10]
![image](https://github.com/chiron-fonts/chiron-sung-hk/assets/108942702/285f14c7-6661-4b8d-8c99-c6cd02b54fcc)

希腊字母 θ 正体未能正确挖空，斜体则没问题。

**Comment by WyxXu** [comment]
![image](https://github.com/chiron-fonts/chiron-sung-hk/assets/108942702/3e14104d-a60a-4b7e-9e76-49efbe42beb1)
您好。感谢您的工作。以上系在OneNote中测试。

**Comment by tamcy** [comment]
你好。早前 θ 問題源於曲線方向有誤，此一錯誤已經修正，並回報至 Source Serif 字體（Italic 版曲線不同，未必會出現相同問題）。閣下既用 OneNote 測試，故推定作業系統是 Windows，而 OneNote 不支援 VF 字體，閣下使用的應是 Instance 版 OTF/TTF。我剛確認過字元 (U+03B8) 的曲線亦應無誤。我在 OneNote 嘗試輸入相關字元，也不相類似問題出現。

![image](https://github.com/chiron-fonts/chiron-sung-hk/assets/959433/f10b5da1-41c8-4d82-88d6-e46081de3bdd)

惟因事忙，匆匆查證恐有疏漏，因此未能能否幫忙確認一下：
1. 所用的作業系統是否 Windows？
2. 使用的是 OTF 還是 TTF 版？
3. 字元 θ 所述的是 U+03B8？
4. 字體版本是否已確認為最新 1.011？（Windows 如用覆蓋方法安裝新版字體，或會有舊版字體殘留，打開檔案所顯示的版本也未必正確，易生誤導。建議先完全移除舊版字體，再安裝新版以確認）

謝謝。

**Comment by WyxXu** [comment]
補充信息：

![image](https://github.com/chiron-fonts/chiron-sung-hk/assets/108942702/6c3e3139-367f-40ac-a2b7-a53afc5f9271)
左為OneNote，右為Word；
系統：win10（專業版 10.0.19045），字體係GitHub下載的最新版字體包，各個字重ttf單獨安裝，安裝方式-為所有用戶安裝，安裝字型後多次重啓；
顯示效果可能與office套件底層是XML有關？

通過 alt-X 確認字符編碼是 3B8 ，alt-X 將 03B8 逆轉爲字符，表現一致（即Sung系列統統顯示異常，Sung Text系列在 SB 字重時異常）

作爲參照：

![image](https://github.com/chiron-fonts/chiron-sung-hk/assets/108942702/0e297819-c818-44a9-aa3a-ca0e5b31440a)
使用 EmEditor，結果相同


![image](https://github.com/chiron-fonts/chiron-sung-hk/assets/108942702/ec19958a-ae66-43f1-9b28-d684486ce907)
vscode+live server 在chrome顯示效果如上。Normal 字重在此不知爲何也顯示異常。

![image](https://github.com/chiron-fonts/chiron-sung-hk/assets/108942702/8f3b41bb-00b2-4705-8b28-bd9922a85cf1)
AsciidocFx（基於Ruby？類markdown，可内嵌HTML）内置預覽似乎全部正常，但生成html到chrome中預覽又是另外一個情況，同前一例子。

PS: 字體在一般文本編輯器中的引用名和在CSS中的引用名似乎不一致，字重不能用縮寫，必須全名。且在文本編輯器中，Text 是在字重後面，到CSS中，字重又必須寫在Text後面。這個無傷大雅，只是略感有失一致性。

我用fontforge打開過ttf查看字形，似乎未發現綫方向等問題，最終也是不解爲何如此。

另：

![image](https://github.com/chiron-fonts/chiron-sung-hk/assets/108942702/1bef4500-10bb-4733-8555-86da6a83ea8a)
Sung 字族不知爲何在某些字體選擇器中顯示為亂碼（内文中顯示正常），可能係編輯器内部引擎差異所致。


感謝作者回覆。

**Comment by WyxXu** [comment]
補充

![image](https://github.com/chiron-fonts/chiron-sung-hk/assets/108942702/81a6d6b5-5c74-47fe-b48d-40771b4dd819)
noetpad

![image](https://github.com/chiron-fonts/chiron-sung-hk/assets/108942702/8b8290c1-6189-492f-b1b2-2a838a69065e)
photoshop

![image](https://github.com/chiron-fonts/chiron-sung-hk/assets/108942702/67c2068a-6e0d-426f-80c8-67f07f15e0ac)
inkscape

![image](https://github.com/chiron-fonts/chiron-sung-hk/assets/108942702/4128b7a6-3397-4897-a804-3015d121279d)
illustrator

**Comment by tamcy** [comment]
先謝謝提供這麼多的參考圖片。另外還想知道，請問閣下有沒有安裝一些像 MacType 一類取代 Windows GDI 渲染引擎的軟件？

**Comment by WyxXu** [comment]
無。不知道有這個。感謝告知，我會嘗試下！

**Comment by tamcy** [comment]
不，我只是在排除一些可能性，並不鼓勵使用。

**Comment by tamcy** [comment]
＠WyxXu 不知是否可幫忙試試，在最新下載昭源宋體 zip 檔的 ttf 目錄中，建立一 demo.html 檔，放入下面的 html 內容，再用 Chrome 開啟，並放大縮小看看，左右兩邊的 θ 是否正常？先謝謝！

----

```html
<!doctype html>
<html lang="zh">
<head>
    <title>Test</title>
    <style>
        @font-face {
            font-family: 'ChironSungHK';
            src: url('ChironSungHK-R.ttf');
            font-weight: normal;
            font-style: normal;
        }

        @font-face {
            font-family: 'ChironSungHK';
            src: url('ChironSungHK-B.ttf');
            font-weight: bold;
            font-style: normal;
        }

        .local {
            font-family: 'ChironSungHK';
        }

        .system {
            font-family: 'Chiron Sung HK';
        }

        body {
            font-weight: normal;
            font-style: normal;
            display: flex;
        }

        div {
            flex: 1;
        }

        p, h1 {
            margin: 0;
            font-size: 12px;
        }
    </style>
</head>
<body>
<div class="col local">
    <h1>Local</h1>
    <p style="font-size: 9px; font-weight: normal;">θ Ѳ</p>
    <p style="font-size: 9px; font-weight: bold;">θ Ѳ</p>
    <p style="font-size: 12px; font-weight: normal;">θ Ѳ</p>
    <p style="font-size: 12px; font-weight: bold;">θ Ѳ</p>
    <p style="font-size: 18px; font-weight: normal;">θ Ѳ</p>
    <p style="font-size: 18px; font-weight: bold;">θ Ѳ</p>
    <p style="font-size: 24px; font-weight: normal;">θ Ѳ</p>
    <p style="font-size: 24px; font-weight: bold;">θ Ѳ</p>
    <p style="font-size: 36px; font-weight: normal;">θ Ѳ</p>
    <p style="font-size: 36px; font-weight: bold;">θ Ѳ</p>
</div>
<div class="col system">
    <h1>System</h1>
    <p style="font-size: 9px; font-weight: normal;">θ Ѳ</p>
    <p style="font-size: 9px; font-weight: bold;">θ Ѳ</p>
    <p style="font-size: 12px; font-weight: normal;">θ Ѳ</p>
    <p style="font-size: 12px; font-weight: bold;">θ Ѳ</p>
    <p style="font-size: 18px; font-weight: normal;">θ Ѳ</p>
    <p style="font-size: 18px; font-weight: bold;">θ Ѳ</p>
    <p style="font-size: 24px; font-weight: normal;">θ Ѳ</p>
    <p style="font-size: 24px; font-weight: bold;">θ Ѳ</p>
    <p style="font-size: 36px; font-weight: normal;">θ Ѳ</p>
    <p style="font-size: 36px; font-weight: bold;">θ Ѳ</p>
</div>
</body>
</html>

```

**Comment by WyxXu** [comment]
![image](https://github.com/chiron-fonts/chiron-sung-hk/assets/108942702/7117e32c-f862-45a8-aa53-b9aa6dbd2a81)
這樣看來就是系統的原因了…… 打擾了，不是字體文件的原因。

希望有朝一日能不再受此困擾。

**Comment by NightFurySL2001** [comment]
试看用浏览器看看这个汉字的字形是不是对应最新版字体？

「膴 (U+81B4)」

**Comment by WyxXu** [comment]
> 试看用浏览器看看这个汉字的字形是不是对应最新版字体？
> 
> 「膴 (U+81B4)」

？

**Comment by NightFurySL2001** [comment]
用上面同样方法测试。
```
<!doctype html>
<html lang="zh">
<head>
    <title>Test</title>
    <style>
        @font-face {
            font-family: 'ChironSungHK';
            src: url('ChironSungHK-R.ttf');
            font-weight: normal;
            font-style: normal;
        }

        @font-face {
            font-family: 'ChironSungHK';
            src: url('ChironSungHK-B.ttf');
            font-weight: bold;
            font-style: normal;
        }

        .local {
            font-family: 'ChironSungHK';
        }

        .system {
            font-family: 'Chiron Sung HK';
        }

        body {
            font-weight: normal;
            font-style: normal;
            display: flex;
        }

        div {
            flex: 1;
        }

        p, h1 {
            margin: 0;
            font-size: 12px;
        }
    </style>
</head>
<body>
<div class="col local">
    <h1>Local</h1>
    <p style="font-size: 18px; font-weight: normal;">「膴 (U+81B4)」</p>
    <p style="font-size: 18px; font-weight: bold;">「膴 (U+81B4)」</p>
</div>
<div class="col system">
    <h1>System</h1>
    <p style="font-size: 18px; font-weight: normal;">「膴 (U+81B4)」</p>
    <p style="font-size: 18px; font-weight: bold;">「膴 (U+81B4)」</p>
</div>
</body>
</html>
```

**Comment by WyxXu** [comment]
![image](https://github.com/chiron-fonts/chiron-sung-hk/assets/108942702/80d679e1-4c9f-4428-84f8-563f3b207b4b)

这和θ的问题有关？

都是sung为什么又跑出来黑体……

**Comment by tamcy** [comment]
@WyxXu 「膴」之前錯誤對映到肉部作「月」的地區，本字體標準作「⺼」。此問題 1.011 版本已修正：
![image](https://github.com/chiron-fonts/chiron-sung-hk/assets/959433/2023c2b1-57b2-4497-861a-4877c7a67c07)

從截圖可見閣下系統字型的「膴」仍是作「月」，即肯定不會是 v1.011 版。

要證實系統中安裝的是否修復 θ 字圖問題的 v1.010 版，可以試試輸入「㗩」字，此字 v1.010 版起羽部改為有勾。

![image](https://github.com/chiron-fonts/chiron-sung-hk/assets/959433/a0452e5a-2ea8-4f42-8884-47573162c3bb)

**Comment by NightFurySL2001** [comment]
> 都是sung为什么又跑出来黑体……

请确认您是在上面测试的字体文件夹内用同样方法测试。

---

这边我感觉是没有完整删除（上面您提到使用“安裝方式-為所有用戶安裝”，但是如果之前是“安装”而已是不会覆盖字体文件的），建议您尝试在 Control Panel - Appearance and Personalisation - Fonts 里面把昭源宋体字体完整删除干净，删除后按F5刷新确保没有弹出新的昭源宋体，重启电脑再确认字体删除干净后，才安装字体。

您也可以顺便看下 Control Panel 里面字体的版本号是不是 v1.011/1.010。

**Comment by tamcy** [comment]
字體應無問題，先關閉。
