### ISSUE TITLE
是否有意支援部份陸標與日標？

### ISSUE THREAD

**Issue by ejmoog** [chiron-fonts/chiron-sung-hk#11]
是否有意支援部份陸標與日標？

「护沪芦」宜用大陸的「户」寫法，而不是「戶」；而日本漢字中「枦粐舮鈩䋆䡎」的「戸」是日本對「盧」的簡化，跟大陸不一樣，宜用「戸」不用「戶」；日本字型「涙」不宜用「户」。

昭源宋體（及黑體）是否有意支援部份陸標及日標？

**Comment by tamcy** [comment]
你好。本字體服務對象是繁體中文使用者，並無打算像思源字體般擴展到 Pan-CJK 用途。

另外，我不太明白閣下所述例子，和為何要支援「部份」陸標與日標（又如何定義「部份」）。尤其是大陸也有將「盧」簡化成「戶/户」的情況（爐→炉），如果不是像思源字體般做地區變體，「炉」應該用「火戸」還是「火户」才能滿足閣下要求？我相信這不會是唯一例子。若要做地區變體，為何只限定「部份」？只做「部份」支援難道真的能滿足有此一需要的人的用場？所以在我看來，如果要符合陸標/日標要求，用陸標/日標字型（或思源 + language-tagging）是最徹底的做法，不湯不水只會製造更多問題。
