### ISSUE TITLE
「坴」字型似乎沒有統一？

### ISSUE THREAD

**Issue by ejmoog** [chiron-fonts/chiron-sung-hk#12]
「熱睦陸」等中, 「熱」的「坴」用「八」，而「睦陸」等字的「坴」卻用「儿」，同一「坴」寫法卻不統一。

**Comment by NightFurySL2001** [comment]
香港参考字形就是这个字形。参考： https://github.com/chiron-fonts/chiron-sans-hk/issues/23

**Comment by tamcy** [comment]
一如 @NightFurySL2001 所說。另參 #13。
