### ISSUE TITLE
「邊」的穴字型問題

### ISSUE THREAD

**Issue by ejmoog** [chiron-fonts/chiron-sung-hk#13]
「邊」中「穴」似乎採用了大陸寫法，但其他「穴字頭」的字卻沒有統一寫法，我建議除了大陸簡化字外，含「穴」的字，要麼寫成「宀八」，要麼寫成「宀ㄦ」。

**Comment by tamcy** [comment]
「邊」中「穴」和坴部件本字體目前處理是跟從[香港電腦漢字參考字形](https://www.ccli.gov.hk/tc/download/reference_glyphs.html)的處理方式，暫時以 Closing as intended 方式關閉。當時選擇的原因是個人書寫習慣。

以印刷字體而言，改成台標個人也沒有太大抗拒，每款字有大概有十餘個字形要修改，暫時沒有時間處理。或者之後沉澱一下再比較看看。

**Comment by tamcy** [comment]
已在宋體 v1.014 (2024/08/08) 、 黑體 v2.515 (2024/08/24) 修改「邊」「坴」字形。
