### ISSUE TITLE
是否有意將宋體和黑體所支援的漢字同步？

### ISSUE THREAD

**Issue by ejmoog** [chiron-fonts/chiron-sung-hk#14]
有些字黑體沒有而宋體有，有些字宋體有而黑體沒有。

請問是否有意通過補全或剔除的方式，使兩個字體所支援的漢字完全相同？

**Comment by tamcy** [comment]
閣下所述情況是繼承自思源黑/宋體。昭源字體原則上不會刪字，是否接受加字則要視乎該字是否在繁體中文地區流通。兩款字型的收字差異既不在昭源字體支援範圍，又不屬流通漢字，因此會留待思源字體處理。
