### ISSUE TITLE
U+03B8 is a solid oval

### ISSUE THREAD

**Issue by zarniwhoop73** [chiron-fonts/chiron-sung-hk#15]
The letters for current monotonic Greek generally look good, and have good accents (dialytika, tonos), making them usable for normal Greek text. But U+03B8 Greek small letter theta is a solid "blob" (a completely filled oval) making this font (v1.015) unusable for Greek text.
[ChironSungHKgreek.pdf](https://github.com/user-attachments/files/17977712/ChironSungHKgreek.pdf)

**Comment by NightFurySL2001** [comment]
Seem to be related to #8, might be an issue from upstream.

**Comment by tamcy** [comment]
For some reason the fixed bug got reintroduced in the latest release. Will investigate.

**Comment by tamcy** [comment]
It seems the fix to U+03B8 was inadvertently undone when along with additions to some new LGC characters. This should now be fixed again in the latest release v1.016.
