### ISSUE TITLE
字型不支援引號直排輸入

### ISSUE THREAD

**Issue by jh1226** [chiron-fonts/chiron-sung-hk#3]
當在直排輸入引號或書名號時，字型顯示了橫排用的標點符號

黑體字型亦出現以下情況

<img width="488" alt="Screenshot 2022-08-01 at 16 38 03" src="https://user-images.githubusercontent.com/22694862/182109009-8640b639-1a07-4c04-8f85-66e14b992ccf.png">

文字出自[《端傳媒》](https://theinitium.com/article/20220801-morning-brief/)

**Comment by tamcy** [comment]
剛上傳了 v1.005（未正式釋出，請使用 Download ZIP 功能下載），試過在 Word 和網頁可正確轉為直排樣式，請看看在你的應用程式是否亦已修復。如果沒問題我會釋出新版本，謝謝。［黑體會在之後處理］

**Comment by jh1226** [comment]
問題已修復

<img width="499" alt="Screenshot 2022-08-03 at 12 09 05" src="https://user-images.githubusercontent.com/22694862/182522238-563e1c55-97c7-4b55-9343-08607dba8f69.png">
復
