### ISSUE TITLE
Incorrectly Linked Web Address

### ISSUE THREAD

**Issue by pan-asian-wok** [chiron-fonts/chiron-sung-hk#4]
Hello Tamcy,

Thank you for your hard work for providing these fonts! I just wanted to let you know that I noticed that the linked web address to 昭源字體 is incorrect. It looks like you're missing the letter "g" in https://chiron-fonts.github.io/

It seems that the linked web address to 昭源字體 in Chiron Hei HK is correct though. This only affects Chiron Sung HK.

**Comment by tamcy** [comment]
Hello, thank you for the report! This is now fixed in the release branch.
