### ISSUE TITLE
Inconsistent Style Between 率 and 玄

### ISSUE THREAD

**Issue by pan-asian-wok** [chiron-fonts/chiron-sung-hk#5]
I wanted to let you know that it seems that 率 appears to be Kangxi Dictionary form, whereas 玄 is more in line with the Chiron Sung font style. This issue is also in Chiron Hei, where I have posted as well. Please see the picture below for reference.

![image](https://user-images.githubusercontent.com/45274474/192688563-411df47c-90cf-4109-99da-b5b185da38e5.png)

**Comment by tamcy** [comment]
May I know which version and configuration of the font are you using? I checked the latest version (1.006) and the first version (1.000) and cannot reproduce this problem (i.e. 率 looks fine). Same for Chiron Hei HK. Thank you!

**Comment by pan-asian-wok** [comment]
I've tried the latest versions of both Chiron Sung and Chiron Hei. I used both LibreOffice and Microsoft Word to replicate the problem. Maybe it's a software problem. I used Character Map and saw that 率 appears like the Chiron style in U+7387, but it looks like Kangxi Dictionary style in U+F961 and U+F9DB.

**Comment by pan-asian-wok** [comment]
Oh... I think I figured it out. The IME that I was using was giving me the CJK Compatibility Ideograph form instead of the regular one. Thank you for looking into it though. I'll close the issue now.
