### ISSUE TITLE
生成PDF文件时 superscript文字问题

### ISSUE THREAD

**Issue by olderflower** [chiron-fonts/chiron-sung-hk#6]
我在使用chiron字体时碰到一个问题，在利用fop生成PDF文件时，superscript 文字会跑出格？ 是什么问题？ 换成其他字体以后就没有问题了。

![g6847](https://user-images.githubusercontent.com/39398416/199440846-703d00a4-6c84-4f61-b9c0-016ed7a1277b.png)

**Comment by tamcy** [comment]
你好。由於我沒有用過 fop，對此軟件陌生，為減少溝通誤會，未知能否提供測試文件及操作步驟，讓我試試在本機執行能否重現問題並尋找解決方法？

**Comment by soolanli** [comment]
1，我尝试了SourceHan和Noto字体，也存在同样的问题，换成SimSun字体或其他字体后问题消失。

2，附件中有四个图片文件，其中，四个图片文件，分别是SourceHan，Noto，ChironSung和SimSun字体在superscript和subscript元素显示样子

3，两个PDF文件，一个使用了ChironSung字体，一个使用了SimSun字体，文件里面有介绍fop的使用方法。

![superscript-SourceHan](https://user-images.githubusercontent.com/39398416/200105959-89195b1b-0d38-49ab-bfdf-21f82fd93864.png)
![superscript-NotoSerifCJK](https://user-images.githubusercontent.com/39398416/200105971-edc0cb44-0771-49dc-b072-453bb75dc1c1.png)
![superscript-ChironSungHK](https://user-images.githubusercontent.com/39398416/200105977-3e88d36c-ab54-4a33-a845-fde036111466.png)
![superscript-SimSun](https://user-images.githubusercontent.com/39398416/200105985-8cd1bb18-2b51-4a4c-a39d-b97b789fdabe.png)

[DocBook.ChironSung.pdf](https://github.com/chiron-fonts/chiron-sung-hk/files/9943205/DocBook.ChironSung.pdf)
[DocBook.SimSun.pdf](https://github.com/chiron-fonts/chiron-sung-hk/files/9943207/DocBook.SimSun.pdf)

**Comment by tamcy** [comment]
我試用了如下 XML 文件:
```xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<fo:root xmlns:fo="http://www.w3.org/1999/XSL/Format">

<fo:layout-master-set>
  <fo:simple-page-master master-name="first"
        page-width="21cm" 
        page-height="29.7cm"
        margin-top="5mm">
     <fo:region-body 
        margin-bottom="4.5in" 
        margin-right="5mm" 
        margin-left="5mm" 
        margin-top="5mm"/>
     <fo:region-after 
        extent="4in" />
  </fo:simple-page-master>

  <fo:simple-page-master master-name="rest"
        page-width="21cm" 
        page-height="29.7cm"  
        margin-right="5mm" 
        margin-left="5mm" 
        margin-top="5mm" 
        margin-bottom="5mm">
     <fo:region-body/>
  </fo:simple-page-master>
  
  <fo:page-sequence-master master-name="A4">
     <fo:repeatable-page-master-alternatives>
        <fo:conditional-page-master-reference master-reference="first" page-position="first"/>
        <fo:conditional-page-master-reference master-reference="rest" page-position="rest"/>
        <fo:conditional-page-master-reference master-reference="rest"/>
     </fo:repeatable-page-master-alternatives>
  </fo:page-sequence-master>
</fo:layout-master-set>
   
  <fo:page-sequence master-reference="A4">
    <fo:flow flow-name="xsl-region-body" font-size="12pt" margin-top="2em" >
			<fo:block font-size="14pt" font-weight="normal" font-family="ChironSungHK">
				123
				<fo:inline vertical-align="sub" font-size="8pt">456</fo:inline>
				7890
			</fo:block>
			<fo:block font-size="14pt" font-weight="normal" font-family="ChironSungHK">
				ABC
				&#x3031;&#x3032;
				<fo:inline vertical-align="super" font-size="8pt">DEFG</fo:inline>
				HIJ
			</fo:block>
			<fo:block font-size="14pt" font-weight="normal" font-family="ChironSungHK">
				ABC
				&#x25CB;&#x25CB;
				<fo:inline vertical-align="super" font-size="8pt">DEFG</fo:inline>
				HIJ
			</fo:block>
    </fo:flow>
   </fo:page-sequence>
</fo:root>
```

執行命令如下:
```
fop -c conf/fop.xconf -fo test.fo -pdf test.pdf
```

![test](https://user-images.githubusercontent.com/959433/200114856-c7ff736a-7a05-487f-aa6a-5bc235cb11c5.png)

可見第二、三行上標的上移距離相同。由此可以推斷，上標過度移位的原因，是 fop 用了字體中最高的字元 (U+3031/U+3032) 做參考，準確點說是直接用了字型檔的 FontBBox 做參照系，而這種做法並不正確。這也是為何使用 Noto CJK/Source Han 系列字型會出現同樣問題，因為本字體的 U+3031/U+3032 字元是繼承自思源字體，並無修改。而同類問題其實已在 Source Han Sans 的 issue list 討論過：https://github.com/adobe-fonts/source-han-sans/issues/88。

這是 fop 本身的 bug。由於 FontBBox 不能亂改，所以本字體無法做任何動作。又由於我對 fop 並不熟悉，所以無法提供任何 workaround。

對了，既然閣下是在為簡體中文文件排版，為何捨思源宋體不用，反而要用專為繁體中文環境而設的昭源黑體呢？畢竟昭源選定的字形未必適合作簡體中文用途。

**Comment by soolanli** [comment]
非常感谢您耐心细致的解答。 选用昭源是出于自己的兴趣。
再次感谢您。

**Comment by olderflower** [comment]
非常感谢您耐心细致的解答。 选用昭源是出于自己的兴趣。
再次感谢您。

**Comment by soolanli** [comment]
我今天尝试了weasyprint, 然后问题解决了。应该是fop的问题。
