### ISSUE TITLE
以纯文本形式提供有改动的字形列表

### ISSUE THREAD

**Issue by NightFurySL2001** [chiron-fonts/chiron-sung-hk#7]
希望您可以提供文本形式的改动（汉字）字形列表，目前以pdf形式提供让后续开发需要提取有点困难。
（另外好奇pdf是如何生成的，不知能不能大概简略介绍下方法）

**Comment by NightFurySL2001** [comment]
（不知可行吗？）

**Comment by tamcy** [comment]
技術可行, 惟暫未有時間處理此事. 
另 PDF 是用 https://gotenberg.dev/ 產生.

**Comment by NightFurySL2001** [comment]
P/S: PDF 484页，第2006项 U+270F0 Ext-B，𧃰的修改字符栏并不是宋体，且没有CID数字。目测来看昭源宋体使用的是思源宋体原本字形？
![image](https://user-images.githubusercontent.com/33471049/230777137-4b02f361-e53b-4c8e-8aa8-6afec8adc15d.png)

**Comment by tamcy** [comment]
其實是因為我的 build script 有 bug 導致生成的 cmap 檔不正確，不幸地在 1.007 發佈後不久才注意到。原始碼已改正，所以下一版會修正此問題。

**Comment by tamcy** [comment]
v1.011 已在 `resources/` 目錄加入 `upstream_differences.json` 檔。
