### ISSUE TITLE
輸入法提問

### ISSUE THREAD

**Issue by eaganlai** [chiron-fonts/chiron-sung-hk#9]
雖與字體無關，但也不知在哪裏問比較妥當，所以就打擾了。

小弟用開倉頡，想問如何可以打出字體中新造的字？Win10 的打字庫似乎並未收藏這些文字，如: 𫬷 𭉝 𡂫 𰇛 𭉓

**Comment by tamcy** [comment]
Windows 倉頡輸入法支援的字碼大概只到 Extension B，閣下提到各字，𫬷字字碼為 U+2BB37 已在 Extension E，所以無法輸入。
我個人沒有太大需要輸入這些字碼，所以也沒有花時間深究直接用作業系統直接輸入字碼的方法。我目前輸入方法大概是（以𫬷字為例）：

1. 如前述，𫬷字字碼為 U+2BB37。在 word 輸入 2BB37 → 按 Alt+X  可以做字碼→字符轉換
2. 利用 [CHISE IDS 漢字検索](https://www.chise.org/ids-find) 網頁輸入「口騎」讓網頁替我組成字符

另外，我知道 "倉頡之友" 網站有一個「[網上倉頡輸入法](https://www.chinesecj.com/ime/cj5.php)」，是支援上述漢字的輸入，由於是網上版，不用安裝。

當然還有其他方法，例如替換 Windows 系統碼表、安裝第三方輸入法等等，但因為沒有親身用過，某些動作或有風險，未敢貿然介紹，請諒。
